### ISSUE TITLE
customer object in promotions.validate body don't need id

### ISSUE THREAD

**Issue by p-zielinski** [voucherifyio/voucherify-js-sdk#146]
https://docs.voucherify.io/reference/validate-promotions-1
![Screenshot 2022-09-12 at 20 41 16](https://user-images.githubusercontent.com/82354717/189731243-26226444-821c-466e-a928-e286451f2301.png)
node_modules/@voucherify/sdk/dist/types/Promotions.d.ts

```
export interface PromotionsValidateParams {
    customer?: Omit<SimpleCustomer, 'object'> & {
        description?: string;
    };
    order?: {
        id?: string;
        source_id?: string;
        items?: OrdersItem[];
        amount?: number;
        metadata?: Record<string, any>;
    };
    metadata?: Record<string, any>;
}
```

Customer should be defined differently. I would suggest to. not use SimpleCustomer at all in this type object

**Comment by darekg11** [comment]
Hey @p-zielinski thank you for reporting this issue.
This issue has been fixed as part of https://github.com/voucherifyio/voucherify-js-sdk/pull/149
I have just released version `2.0.14` of the SDK where this issue should be fixed. New version should be shortly available in the NPM registry.

Closing.
