### ISSUE TITLE
There's no hierarchy (promotions object) and product.name (discount object) if type discount is unit - validate promotions

### ISSUE THREAD

**Issue by patricioo1** [voucherifyio/voucherify-js-sdk#147]
![Screenshot 2022-09-12 at 20 58 28](https://user-images.githubusercontent.com/77458595/189735043-354b39d2-744f-45b2-b43e-d51dabea40f1.png)
![Screenshot 2022-09-12 at 20 58 53](https://user-images.githubusercontent.com/77458595/189735731-f3036f12-9986-48fd-98be-1b88deb79420.png)
node_modules/@voucherify/sdk/dist/types/Promotions.d.ts

![Screenshot 2022-09-12 at 21 04 10](https://user-images.githubusercontent.com/77458595/189735297-193876a4-c7fb-46bd-8e41-929ee2dd5726.png)
![Screenshot 2022-09-12 at 20 40 54](https://user-images.githubusercontent.com/77458595/189735815-86157d69-0a87-46a4-a49a-eabe34acac96.png)
node_modules/@voucherify/sdk/dist/types/DiscountVoucher.d.ts

https://docs.voucherify.io/reference/validate-promotions-1

**Comment by darekg11** [comment]
Hey @patricioo1  thank you for reporting this issue.
This issue has been fixed as part of https://github.com/voucherifyio/voucherify-js-sdk/pull/149
I have just released version `2.0.14` of the SDK where this issue should be fixed. New version should be shortly available in the NPM registry.

Closing.
