### ISSUE TITLE
more missing types in validate promotion endpoint

### ISSUE THREAD

**Issue by patricioo1** [voucherifyio/voucherify-js-sdk#148]
Now it's look like that.

![Screenshot 2022-09-13 at 09 35 06](https://user-images.githubusercontent.com/77458595/189839769-f1aaefbe-885b-452e-bd2c-d1bdffcd0799.png)

But more types is missing like applied_discount_amount at main level, a few types in order object

<img width="947" alt="Screenshot 2022-09-13 at 09 29 04" src="https://user-images.githubusercontent.com/77458595/189839948-e7848224-1cf2-4f22-b21a-219a14e07819.png">

![Screenshot 2022-09-13 at 09 32 11](https://user-images.githubusercontent.com/77458595/189840020-b924398b-4f8e-410d-8b09-b58937d4adfd.png)

node_modules/@voucherify/sdk/dist/types/Promotions.d.ts

**Comment by darekg11** [comment]
Hey @patricioo1  thank you for reporting this issue.
This issue has been fixed as part of https://github.com/voucherifyio/voucherify-js-sdk/pull/149
I have just released version `2.0.14` of the SDK where this issue should be fixed. New version should be shortly available in the NPM registry.

Closing.
