### ISSUE TITLE
error data is missing from response types

### ISSUE THREAD

**Issue by davidwoodmansee** [voucherifyio/voucherify-js-sdk#176]
A request such as validateVoucher can return a meaningful error message such as the result of validation rules. I would want to use those error details to give better feedback to the end user. The typescript type definitions do not seem to be aware of the error properties.

**Comment by darekg11** [comment]
Hello @davidwoodmansee 
Sorry for the late response, I have just released version `2.1.4` of the SDK which should now include `error` property returned, you can see changes in: https://github.com/voucherifyio/voucherify-js-sdk/pull/179

Please let me know if this is solving your issue.
In case of no response this issue will be closed by the end of the week on 13.01.2023

**Comment by darekg11** [comment]
I am closing this issue, if you feel like your issue is still not resolved, please feel free to re-open it with details.
