### ISSUE TITLE
Implement advanced filters in vouchers.list method

### ISSUE THREAD

**Issue by afjlambert-gv** [voucherifyio/voucherify-js-sdk#197]
It doesn't seem to be possible to specify advanced filters (https://docs.voucherify.io/reference/listing#advanced-filters-for-fetching-resources) in the `vouchers.list` method. Can you add these so we can do proper pagination? We now need to filter the results after fetching all the vouchers.

**Comment by darekg11** [comment]
Dear @afjlambert-gv thank tou for reporting this issue.
Required changes has been introduced in this PR: https://github.com/voucherifyio/voucherify-js-sdk/pull/198
PR that triggered new version release: https://github.com/voucherifyio/voucherify-js-sdk/pull/199

Fix is included in version 2.1.9 and it should be available in NPM registry shortly.

Examples of requests with `filters`:
**Quering by active example:**
```
voucherify.vouchers
	.list({
		limit: 10,
		page: 1,
		filters: {
			junction: 'AND',
			active: {
				conditions: {
					$active: true,
				},
			},
		},
	})
	.then(function (result) {
		console.log(result)
	})
	.catch(function (err) {
		console.error(err)
	})
```

**Quering by boolean metadata example:**
```
voucherify.vouchers
	.list({
		limit: 10,
		page: 1,
		filters: {
			junction: 'AND',
			'metadata.test': {
				conditions: {
					$is: true,
				},
			},
		},
	})
	.then(function (result) {
		console.log(result)
	})
	.catch(function (err) {
		console.error(err)
	})
```

I will close this issue now, if you feel like something is still missing, please feel free to reopen
