### ISSUE TITLE
Order by expiration date

### ISSUE THREAD

**Issue by afjlambert-gv** [voucherifyio/voucherify-js-sdk#200]
We'd like to be able to order the vouchers for a given user by expiration_date. 

Like this: `vouchers.list({customer: "...", order: "-expiration_date"})`

This doesn't seem to be possible. We get this error:

> Type '"-expiration_date"' is not assignable to type '"-created_at" | "created_at" | "-updated_at" | "updated_at" | "-type" | "type" | "-code" | "code" | "-campaign" | "campaign" | "-category" | "category" | undefined'.ts(2322)

Is this a feature that you'd be willing to implement?

Thanks a lot!

**Comment by darekg11** [comment]
Hello @afjlambert-gv such ordering is not support by API.
This GitHub repository is dedicated to SDK and issues with missing methods, types etc.
If you wish to propose a change in API please contact our support via `support@voucherify.io`
