### ISSUE TITLE
missing promise type returned from list campaigns 

### ISSUE THREAD

**Issue by sh-shamsan** [voucherifyio/voucherify-js-sdk#201]
Hello, 
The response type from list campaigns is missing, I could create a PR if it's just adding `<T.CampaignsListResponse>` to this: 
https://github.com/voucherifyio/voucherify-js-sdk/blob/dd7a898e081fa640c73e24e8e14ff0cea2b3dfab/packages/sdk/src/Campaigns.ts#L71

**Comment by darekg11** [comment]
Dear @sh-shamsan  thank tou for reporting this issue. You are correct, this was just missing usage of type for return value.

Required changes has been introduced in this PR: https://github.com/voucherifyio/voucherify-js-sdk/pull/203
PR that triggered new version release: https://github.com/voucherifyio/voucherify-js-sdk/pull/204

Fix is included in version 2.2.0 and it should be available in NPM registry shortly.

I will close this issue now, if you feel like something is still missing, please feel free to reopen
