### ISSUE TITLE
ValidationsValidateVoucherResponse interface incomplete

### ISSUE THREAD

**Issue by Luifr** [voucherifyio/voucherify-js-sdk#206]
Shouldnt the discount field in ValidationsValidateVoucherResponse have a discount for fixed type vouchers?

Currently it looks like this: `discount?: DiscountAmount | DiscountUnit | DiscountPercent;`

It is missing DiscountFixed that would use `DiscountVouchersTypesEnum.FIXED`

**Comment by darekg11** [comment]
Dear @Luifr  thank you for reporting this issue.

Required changes has been introduced in this PR: https://github.com/voucherifyio/voucherify-js-sdk/pull/207
PR that triggered new version release: https://github.com/voucherifyio/voucherify-js-sdk/pull/208

Fix is included in version 2.2.1 and it should be available in NPM registry shortly.

I will close this issue now, if you feel like something is still missing, please feel free to reopen
