### ISSUE TITLE
Add support for new Qualifications API

### ISSUE THREAD

**Issue by akshitkrnagpal** [voucherifyio/voucherify-js-sdk#257]
It would be great if we can add support for Qualifications API.
https://docs.voucherify.io/reference/check-eligibility

**Comment by darekg11** [comment]
Hello @akshitkrnagpal please check newest version of SDK - `2.7.0` where support for Qualifications API has been added:
https://github.com/voucherifyio/voucherify-js-sdk/blob/main/packages/sdk/CHANGELOG.md#270
