### ISSUE TITLE
Voucher codes with "%" sign result in "voucher not found" error

### ISSUE THREAD

**Issue by alex-all3dp** [voucherifyio/voucherify-js-sdk#94]
After upgrading from SDK version `1.0.1` to `1.3.0` we receive `voucher not found` as a result of the voucher validation if the voucher code contains a `%`.
When reverting back to `1.0.1` the validation of these vouchers works normally.
Please advise :)

**Comment by pannga** [comment]
@alex-all3dp please use newest SDK `1.3.1` from npmjs.
